### ISSUE TITLE
Transactions not displayed and false amount.

### ISSUE THREAD

**Issue by Sofarlemineur** [XDagger/goXdagWallet#13]
Hi,
I have made just 2 quick transaction of 100XDAG each, at first i had 213 XDAG in my wallet.
TX is showed in the block explorer, but not in the wallet, and my total amount is now of 207 XDAG, when it should be 13XDAG...

 Wallet adress : k+ccOPhuqH5dnWiz0ILFayIS4r/cFTcW

Thanks for your work.

**Comment by FSOL06** [comment]
@Sofarlemineur Is this problem still alive ?
