### ISSUE TITLE
Unable to backup a wallet where you havent set up a password

### ISSUE THREAD

**Issue by Sofarlemineur** [XDagger/goXdagWallet#15]
Hi,

i have an old wallet that is use usually for some test, where i havent setup a password, if i backup it by copying files in the folder of this new version, i cannot open it as i havent setup a password, ths wallet stay stuck to ask a password...

**Comment by swordlet** [comment]
allow empty password in v0.44

**Comment by Sofarlemineur** [comment]
Fantastic!!
Thanks for your work
