### ISSUE TITLE
0.5.0 - Bad version in "about" tab

### ISSUE THREAD

**Issue by FSOL06** [XDagger/goXdagWallet#18]
![image](https://user-images.githubusercontent.com/97795464/187545270-171b13a0-a2bf-48f8-a250-81be1c6baaa5.png)

See picture.

**Comment by swordlet** [comment]
thanks to remind

**Comment by FSOL06** [comment]
> thanks to remind

Please contact me on XDAG Discord. Thanks !

**Comment by FSOL06** [comment]
Corrected with release 0.5.1
