### ISSUE TITLE
0.5.2 - Import wallet - Translation of some words missing

### ISSUE THREAD

**Issue by FSOL06** [XDagger/goXdagWallet#28]
![image](https://user-images.githubusercontent.com/97795464/192105797-388daf9d-3c25-4e46-b507-70f62dfd7c75.png)

I thinks theses works are given by Windows. Possible to translate them ?

**Comment by FSOL06** [comment]
Same request for apparence : 

![image](https://user-images.githubusercontent.com/97795464/192107140-189334ff-ef6d-4964-a2bf-b2c6130697c8.png)

**Comment by swordlet** [comment]
These words is in GUI library,  this GUI component does not support i18n yet.

**Comment by FSOL06** [comment]
Ok thanks. So I close this issue.
