### ISSUE TITLE
Connecting pool...

### ISSUE THREAD

**Issue by GV78** [XDagger/goXdagWallet#49]
Hello,
I have had my Wallet stuck at "connecting pool..." for about 2 weeks now.
I was in 0.5.1 but I have the same problem importing my wallet in 0.5.4.
same problem when importing on another PC ( Win11, Win10 )

**Comment by iGodPro** [comment]
If your wallet keep connecting, please open "wallet_config.json" and change pool address to
pool.xdag.org:13656
it will work again（V0.5.4）
Please join our discord, it will release latest info:
https://discord.gg/Nf72gd9

**Comment by GV78** [comment]
Great it works, thanks.
looking at the sources I see that it will be fixed in version 0.5.5.
